[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "echo DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy > .env",
  "npm install"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build:backend"
]

[start]
cmd = "rm -f .env && npx prisma migrate deploy && node dist/main"
