[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "echo 'DATABASE_URL=postgresql://user:pass@localhost:5432/db' > .env",
  "npx prisma generate",
  "npm run build:backend",
  "rm .env"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
